2020-06-12T19:41:17.960284+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/log.py", line 96, in __init__
2020-06-12T19:41:17.960285+00:00 app[web.1]:     if self._echo_map[echo] <= logging.INFO and not self.logger.handlers:
2020-06-12T19:41:17.960285+00:00 app[web.1]: KeyError: 'False'
2020-06-12T19:41:17.960646+00:00 app[web.1]: [2020-06-12 19:41:17 +0000] [11] [INFO] Worker exiting (pid: 11)
2020-06-12T19:41:18.217977+00:00 app[web.1]: [2020-06-12 19:41:18 +0000] [4] [INFO] Shutting down: Master
2020-06-12T19:41:18.218110+00:00 app[web.1]: [2020-06-12 19:41:18 +0000] [4] [INFO] Reason: Worker failed to boot.
2020-06-12T19:41:18.293980+00:00 heroku[web.1]: Process exited with status 3
2020-06-12T19:41:18.328313+00:00 heroku[web.1]: State changed from up to crashed
2020-06-12T19:51:15.226679+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=c-finance.herokuapp.com request_id=3a16d107-3455-4732-ac1e-9670bb951d9c fwd="70.23.49.147" dyno= connect= service= status=503 bytes= protocol=https
2020-06-12T19:51:16.034313+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=c-finance.herokuapp.com request_id=d9921a96-35f7-4c4a-a611-d25a14271f95 fwd="70.23.49.147" dyno= connect= service= status=503 bytes= protocol=https
2020-06-12T19:54:15.116315+00:00 heroku[web.1]: State changed from crashed to starting
2020-06-12T19:54:22.706728+00:00 heroku[web.1]: Starting process with command `gunicorn app:app`
2020-06-12T19:54:26.460338+00:00 app[web.1]: [2020-06-12 19:54:26 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-06-12T19:54:26.461328+00:00 app[web.1]: [2020-06-12 19:54:26 +0000] [4] [INFO] Listening at: http://0.0.0.0:6491 (4)
2020-06-12T19:54:26.461505+00:00 app[web.1]: [2020-06-12 19:54:26 +0000] [4] [INFO] Using worker: sync
2020-06-12T19:54:26.470114+00:00 app[web.1]: [2020-06-12 19:54:26 +0000] [10] [INFO] Booting worker with pid: 10
2020-06-12T19:54:26.506335+00:00 app[web.1]: [2020-06-12 19:54:26 +0000] [11] [INFO] Booting worker with pid: 11
2020-06-12T19:54:27.055117+00:00 heroku[web.1]: State changed from starting to up
2020-06-12T19:54:30.196771+00:00 app[web.1]: [2020-06-12 19:54:30 +0000] [11] [ERROR] Exception in worker process
2020-06-12T19:54:30.196793+00:00 app[web.1]: Traceback (most recent call last):
2020-06-12T19:54:30.196795+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-06-12T19:54:30.196796+00:00 app[web.1]:     worker.init_process()
2020-06-12T19:54:30.196796+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-06-12T19:54:30.196797+00:00 app[web.1]:     self.load_wsgi()
2020-06-12T19:54:30.196797+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-06-12T19:54:30.196797+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2020-06-12T19:54:30.196798+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-06-12T19:54:30.196799+00:00 app[web.1]:     self.callable = self.load()
2020-06-12T19:54:30.196799+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-06-12T19:54:30.196799+00:00 app[web.1]:     return self.load_wsgiapp()
2020-06-12T19:54:30.196800+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-06-12T19:54:30.196800+00:00 app[web.1]:     return util.import_app(self.app_uri)
2020-06-12T19:54:30.196800+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
2020-06-12T19:54:30.196801+00:00 app[web.1]:     mod = importlib.import_module(module)
2020-06-12T19:54:30.196801+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
2020-06-12T19:54:30.196802+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2020-06-12T19:54:30.196802+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2020-06-12T19:54:30.196803+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2020-06-12T19:54:30.196803+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
2020-06-12T19:54:30.196803+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
2020-06-12T19:54:30.196804+00:00 app[web.1]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
2020-06-12T19:54:30.196804+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-06-12T19:54:30.196805+00:00 app[web.1]:   File "/app/app.py", line 40, in <module>
2020-06-12T19:54:30.196805+00:00 app[web.1]:     db.create_all()
2020-06-12T19:54:30.196805+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1033, in create_all
2020-06-12T19:54:30.196806+00:00 app[web.1]:     self._execute_for_all_tables(app, bind, 'create_all')
2020-06-12T19:54:30.196807+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1025, in _execute_for_all_tables
2020-06-12T19:54:30.196807+00:00 app[web.1]:     op(bind=self.get_engine(app, bind), **extra)
2020-06-12T19:54:30.196807+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 956, in get_engine
2020-06-12T19:54:30.196807+00:00 app[web.1]:     return connector.get_engine()
2020-06-12T19:54:30.196808+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 561, in get_engine
2020-06-12T19:54:30.196808+00:00 app[web.1]:     self._engine = rv = self._sa.create_engine(sa_url, options)
2020-06-12T19:54:30.196808+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 966, in create_engine
2020-06-12T19:54:30.196809+00:00 app[web.1]:     return sqlalchemy.create_engine(sa_url, **engine_opts)
2020-06-12T19:54:30.196810+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 479, in create_engine
2020-06-12T19:54:30.196810+00:00 app[web.1]:     return strategy.create(*args, **kwargs)
2020-06-12T19:54:30.196810+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 177, in create
2020-06-12T19:54:30.196810+00:00 app[web.1]:     engine = engineclass(pool, dialect, u, **engine_args)
2020-06-12T19:54:30.196811+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1876, in __init__
2020-06-12T19:54:30.196811+00:00 app[web.1]:     self.echo = echo
2020-06-12T19:54:30.196817+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/log.py", line 222, in __set__
2020-06-12T19:54:30.196818+00:00 app[web.1]:     instance_logger(instance, echoflag=value)
2020-06-12T19:54:30.196818+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/log.py", line 199, in instance_logger
2020-06-12T19:54:30.196819+00:00 app[web.1]:     logger = InstanceLogger(echoflag, name)
2020-06-12T19:54:30.196819+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/log.py", line 96, in __init__
2020-06-12T19:54:30.196819+00:00 app[web.1]:     if self._echo_map[echo] <= logging.INFO and not self.logger.handlers:
2020-06-12T19:54:30.196820+00:00 app[web.1]: KeyError: 'False'
2020-06-12T19:54:30.197138+00:00 app[web.1]: [2020-06-12 19:54:30 +0000] [11] [INFO] Worker exiting (pid: 11)
2020-06-12T19:54:30.201604+00:00 app[web.1]: [2020-06-12 19:54:30 +0000] [10] [ERROR] Exception in worker process
2020-06-12T19:54:30.201607+00:00 app[web.1]: Traceback (most recent call last):
2020-06-12T19:54:30.201608+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-06-12T19:54:30.201609+00:00 app[web.1]:     worker.init_process()
2020-06-12T19:54:30.201610+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-06-12T19:54:30.201610+00:00 app[web.1]:     self.load_wsgi()
2020-06-12T19:54:30.201610+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-06-12T19:54:30.201611+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2020-06-12T19:54:30.201612+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-06-12T19:54:30.201612+00:00 app[web.1]:     self.callable = self.load()
2020-06-12T19:54:30.201612+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-06-12T19:54:30.201613+00:00 app[web.1]:     return self.load_wsgiapp()
2020-06-12T19:54:30.201613+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-06-12T19:54:30.201613+00:00 app[web.1]:     return util.import_app(self.app_uri)
2020-06-12T19:54:30.201614+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
2020-06-12T19:54:30.201614+00:00 app[web.1]:     mod = importlib.import_module(module)
2020-06-12T19:54:30.201615+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
2020-06-12T19:54:30.201616+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2020-06-12T19:54:30.201616+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2020-06-12T19:54:30.201616+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2020-06-12T19:54:30.201617+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
2020-06-12T19:54:30.201617+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
2020-06-12T19:54:30.201617+00:00 app[web.1]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
2020-06-12T19:54:30.201618+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-06-12T19:54:30.201618+00:00 app[web.1]:   File "/app/app.py", line 40, in <module>
2020-06-12T19:54:30.201619+00:00 app[web.1]:     db.create_all()
2020-06-12T19:54:30.201619+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1033, in create_all
2020-06-12T19:54:30.201620+00:00 app[web.1]:     self._execute_for_all_tables(app, bind, 'create_all')
2020-06-12T19:54:30.201630+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1025, in _execute_for_all_tables
2020-06-12T19:54:30.201630+00:00 app[web.1]:     op(bind=self.get_engine(app, bind), **extra)
2020-06-12T19:54:30.201631+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 956, in get_engine
2020-06-12T19:54:30.201631+00:00 app[web.1]:     return connector.get_engine()
2020-06-12T19:54:30.201631+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 561, in get_engine
2020-06-12T19:54:30.201632+00:00 app[web.1]:     self._engine = rv = self._sa.create_engine(sa_url, options)
2020-06-12T19:54:30.201632+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 966, in create_engine
2020-06-12T19:54:30.201632+00:00 app[web.1]:     return sqlalchemy.create_engine(sa_url, **engine_opts)
2020-06-12T19:54:30.201661+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 479, in create_engine
2020-06-12T19:54:30.201662+00:00 app[web.1]:     return strategy.create(*args, **kwargs)
2020-06-12T19:54:30.201662+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 177, in create
2020-06-12T19:54:30.201663+00:00 app[web.1]:     engine = engineclass(pool, dialect, u, **engine_args)
2020-06-12T19:54:30.201663+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1876, in __init__
2020-06-12T19:54:30.201664+00:00 app[web.1]:     self.echo = echo
2020-06-12T19:54:30.201664+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/log.py", line 222, in __set__
2020-06-12T19:54:30.201664+00:00 app[web.1]:     instance_logger(instance, echoflag=value)
2020-06-12T19:54:30.201665+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/log.py", line 199, in instance_logger
2020-06-12T19:54:30.201665+00:00 app[web.1]:     logger = InstanceLogger(echoflag, name)
2020-06-12T19:54:30.201665+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/log.py", line 96, in __init__
2020-06-12T19:54:30.201666+00:00 app[web.1]:     if self._echo_map[echo] <= logging.INFO and not self.logger.handlers:
2020-06-12T19:54:30.201666+00:00 app[web.1]: KeyError: 'False'
2020-06-12T19:54:30.202095+00:00 app[web.1]: [2020-06-12 19:54:30 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-06-12T19:54:30.357202+00:00 app[web.1]: Traceback (most recent call last):
2020-06-12T19:54:30.357209+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 209, in run
2020-06-12T19:54:30.357733+00:00 app[web.1]:     self.sleep()
2020-06-12T19:54:30.357770+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 357, in sleep
2020-06-12T19:54:30.358221+00:00 app[web.1]:     ready = select.select([self.PIPE[0]], [], [], 1.0)
2020-06-12T19:54:30.358257+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2020-06-12T19:54:30.358479+00:00 app[web.1]:     self.reap_workers()
2020-06-12T19:54:30.358484+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2020-06-12T19:54:30.358745+00:00 app[web.1]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2020-06-12T19:54:30.358831+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2020-06-12T19:54:30.358853+00:00 app[web.1]: 
2020-06-12T19:54:30.358854+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-12T19:54:30.358854+00:00 app[web.1]: 
2020-06-12T19:54:30.358858+00:00 app[web.1]: Traceback (most recent call last):
2020-06-12T19:54:30.358878+00:00 app[web.1]:   File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2020-06-12T19:54:30.359004+00:00 app[web.1]:     sys.exit(run())
2020-06-12T19:54:30.359027+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
2020-06-12T19:54:30.359158+00:00 app[web.1]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2020-06-12T19:54:30.359182+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
2020-06-12T19:54:30.359351+00:00 app[web.1]:     super().run()
2020-06-12T19:54:30.359372+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
2020-06-12T19:54:30.359504+00:00 app[web.1]:     Arbiter(self).run()
2020-06-12T19:54:30.359527+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
2020-06-12T19:54:30.360205+00:00 app[web.1]:     self.halt(reason=inst.reason, exit_status=inst.exit_status)
2020-06-12T19:54:30.360264+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
2020-06-12T19:54:30.360601+00:00 app[web.1]:     self.stop()
2020-06-12T19:54:30.360604+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
2020-06-12T19:54:30.360959+00:00 app[web.1]:     time.sleep(0.1)
2020-06-12T19:54:30.360996+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2020-06-12T19:54:30.361163+00:00 app[web.1]:     self.reap_workers()
2020-06-12T19:54:30.361167+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2020-06-12T19:54:30.361387+00:00 app[web.1]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2020-06-12T19:54:30.361423+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2020-06-12T19:54:30.455122+00:00 heroku[web.1]: Process exited with status 1
2020-06-12T19:54:30.498905+00:00 heroku[web.1]: State changed from up to crashed